#!/bin/sh
# shellcheck shell=dash
# shellcheck disable=SC2034
# SPDX-License-Identifier: Apache-2.0
# ISIRO runtime installer
#
# Quick install:
#   curl -fsSL https://isiro.ai/install.sh | sh
#
# Inspect before running (recommended):
#   curl -fsSL https://isiro.ai/install.sh -o install.sh
#   less install.sh
#   curl -fsSL https://isiro.ai/install.sh.sha256 -o install.sh.sha256
#   sha256sum -c install.sh.sha256          # Linux
#   shasum -a 256 -c install.sh.sha256      # macOS
#   sh install.sh
#
# View script source:
#   https://github.com/isiroai/isiro/blob/main/install.sh
#
# Partial-execution safe: logic in functions; main invoked only on final line.

set -eu

# ISIRO_RELEASE_CONSTANTS_BEGIN — generated by scripts/release/generate_release_artifacts.py
PRODUCT_VERSION="${ISIRO_PRODUCT_VERSION:-0.1.0}"
EULA_VERSION="0.1"
EULA_URL="https://isiro.ai/eula"
INSTALL_BASE_URL="${ISIRO_INSTALL_BASE_URL:-https://isiro.ai/download}"
INSTALL_SCRIPT_URL="${ISIRO_INSTALL_SCRIPT_URL:-https://isiro.ai/install.sh}"
INSTALL_SCRIPT_SHA256_URL="${ISIRO_INSTALL_SCRIPT_SHA256_URL:-https://isiro.ai/install.sh.sha256}"
SCRIPT_SOURCE_URL="${ISIRO_SCRIPT_SOURCE_URL:-https://github.com/isiroai/isiro/blob/main/install.sh}"
RUNTIME_REGISTRY="${ISIRO_RUNTIME_REGISTRY:-isiro/isiro-runtime}"
RUNTIME_TAG="0.1.0"
# Prefer digest from release-manifest.json; otherwise pull by tag.
RUNTIME_DIGEST="${ISIRO_RUNTIME_DIGEST:-}"
# ISIRO_RELEASE_CONSTANTS_END
LAUNCHER_SRC_NAME="isiro-launcher.sh"
SERVE_ENTRY_SRC_NAME="isiro-serve-entry.sh"
CLI_LIGHT_ENTRY_SRC_NAME="isiro-cli-light-entry.sh"
EXTRACT_SRC_NAME="docker_extract_image_path.sh"
INSTALL_ASSETS_SRC_NAME="install_runtime_assets.sh"
COMPLETION_SRC_NAME="isiro-completion.bash"
UNINSTALL_SRC_NAME="isiro-uninstall.sh"

ISIRO_HOME="${ISIRO_HOME:-$HOME/.isiro}"
BIN_DIR="${ISIRO_HOME}/bin"
LIB_DIR="${ISIRO_HOME}/lib"
TEMP_DIR=""

red=""
plain=""
if [ -t 2 ] && command -v tput >/dev/null 2>&1; then
  red="$( (/usr/bin/tput bold 2>/dev/null || :; /usr/bin/tput setaf 1 2>/dev/null || :) 2>&- )"
  plain="$( (/usr/bin/tput sgr0 2>/dev/null || :) 2>&- )"
fi

status() { echo ">>> $*" >&2; }
error() { echo "${red}ERROR:${plain} $*" >&2; exit 1; }
warning() { echo "${red}WARNING:${plain} $*" >&2; }

require_tools() {
  local missing="" tool
  for tool in "$@"; do
    if ! command -v "$tool" >/dev/null 2>&1; then
      missing="${missing} ${tool}"
    fi
  done
  if [ -n "$missing" ]; then
    status "The following tools are required but missing:"
    for tool in $missing; do
      echo "  - ${tool# }" >&2
    done
    case "$missing" in
      *docker*)
        status "Install Docker: https://docs.docker.com/get-docker/"
        ;;
    esac
    exit 1
  fi
}

cleanup() {
  if [ -n "$TEMP_DIR" ] && [ -d "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
  fi
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

is_darwin() {
  [ "$(uname -s)" = "Darwin" ]
}

is_linux() {
  [ "$(uname -s)" = "Linux" ]
}

preflight_install() {
  case "$(uname -s)" in
    Linux|Darwin) ;;
    *) error "Unsupported OS: $(uname -s). ISIRO supports Linux and macOS." ;;
  esac
  require_tools docker
  if ! docker info >/dev/null 2>&1; then
    if is_darwin; then
      error "Docker is installed but Docker Desktop is not running. Open Docker Desktop, wait until it is ready, then retry."
    else
      error "Docker is installed but the daemon is not running. Start it (e.g. sudo systemctl start docker) and retry."
    fi
  fi
  if is_darwin; then
    status "macOS: launcher and isiro compile are supported."
    status "GPU inference (isiro serve) requires Linux with an NVIDIA GPU."
  fi
}

detect_rc_file() {
  local shell_name="${SHELL:-}"
  if is_darwin; then
    case "$shell_name" in
      */zsh) echo "$HOME/.zshrc"; return ;;
      */bash) echo "$HOME/.bash_profile"; return ;;
    esac
    if [ -f "$HOME/.zshrc" ]; then
      echo "$HOME/.zshrc"
      return
    fi
    echo "$HOME/.profile"
    return
  fi
  case "$shell_name" in
    */zsh) echo "$HOME/.zshrc"; return ;;
    */bash) echo "$HOME/.bashrc"; return ;;
  esac
  echo "$HOME/.profile"
}

append_path_line() {
  local rc="$1"
  local line='export PATH="$HOME/.isiro/bin:$PATH"'
  mkdir -p "$(dirname "$rc")"
  touch "$rc"
  if grep -Fq '.isiro/bin' "$rc" 2>/dev/null; then
    return 1
  fi
  if grep -Fq "BEGIN ISIRO runtime launcher" "$rc" 2>/dev/null; then
    return 1
  fi
  {
    echo ""
    echo "# BEGIN ISIRO runtime launcher (managed by install.sh)"
    echo "$line"
    echo "# END ISIRO runtime launcher"
  } >> "$rc"
  return 0
}

append_bash_completion_loader() {
  local rc="$1"
  local begin="# BEGIN ISIRO bash completion (managed by install.sh)"
  local end="# END ISIRO bash completion"
  local line='[[ -f "${HOME}/.bash_completion.d/isiro" ]] && . "${HOME}/.bash_completion.d/isiro"'
  mkdir -p "$(dirname "$rc")"
  touch "$rc"
  if grep -Fq "BEGIN ISIRO bash completion" "$rc" 2>/dev/null; then
    return 1
  fi
  {
    echo ""
    echo "$begin"
    echo "$line"
    echo "$end"
  } >> "$rc"
  return 0
}

record_eula_acceptance() {
  mkdir -p "$ISIRO_HOME"
  local ts
  if command -v python3 >/dev/null 2>&1; then
    ts="$(python3 - <<'PY'
from datetime import datetime, timezone
print(datetime.now(timezone.utc).isoformat())
PY
)"
  else
    ts="$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u)"
  fi
  cat > "${ISIRO_HOME}/eula_acceptance.json" <<EOF
{
  "eula_version": "${EULA_VERSION}",
  "eula_url": "${EULA_URL}",
  "accepted_at": "${ts}",
  "method": "install.sh"
}
EOF
}

eula_already_accepted() {
  local marker="${ISIRO_HOME}/eula_acceptance.json"
  if [ ! -f "$marker" ]; then
    return 1
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$marker" "$EULA_VERSION" <<'PY'
import json, sys
path, expected = sys.argv[1:3]
try:
    data = json.load(open(path, encoding="utf-8"))
except Exception:
    raise SystemExit(1)
raise SystemExit(0 if data.get("eula_version") == expected else 1)
PY
    return $?
  fi
  grep -Fq "\"eula_version\": \"${EULA_VERSION}\"" "$marker" 2>/dev/null
}

read_prior_product_version() {
  local manifest="${ISIRO_HOME}/release-manifest.json"
  if [ ! -f "$manifest" ]; then
    return 0
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$manifest" <<'PY'
import json, sys
from pathlib import Path
path = Path(sys.argv[1])
if not path.is_file():
    raise SystemExit(0)
data = json.loads(path.read_text(encoding="utf-8"))
print((data.get("product_version") or "").strip())
PY
    return 0
  fi
  grep '"product_version"' "$manifest" 2>/dev/null \
    | sed 's/.*"product_version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' \
    | head -1
}

install_launcher_from_dir() {
  local root="$1"
  mkdir -p "$BIN_DIR" "$LIB_DIR" "${ISIRO_HOME}/wheels"
  cp "${root}/bin/isiro" "${BIN_DIR}/isiro"
  chmod +x "${BIN_DIR}/isiro"
  cp "${root}/lib/${SERVE_ENTRY_SRC_NAME}" "${LIB_DIR}/${SERVE_ENTRY_SRC_NAME}"
  chmod +x "${LIB_DIR}/${SERVE_ENTRY_SRC_NAME}"
  cp "${root}/lib/${CLI_LIGHT_ENTRY_SRC_NAME}" "${LIB_DIR}/${CLI_LIGHT_ENTRY_SRC_NAME}"
  chmod +x "${LIB_DIR}/${CLI_LIGHT_ENTRY_SRC_NAME}"
  cp "${root}/lib/${EXTRACT_SRC_NAME}" "${LIB_DIR}/${EXTRACT_SRC_NAME}"
  chmod +x "${LIB_DIR}/${EXTRACT_SRC_NAME}"
  cp "${root}/lib/${INSTALL_ASSETS_SRC_NAME}" "${LIB_DIR}/${INSTALL_ASSETS_SRC_NAME}"
  chmod +x "${LIB_DIR}/${INSTALL_ASSETS_SRC_NAME}"
  if [ -f "${root}/lib/${COMPLETION_SRC_NAME}" ]; then
    cp "${root}/lib/${COMPLETION_SRC_NAME}" "${LIB_DIR}/${COMPLETION_SRC_NAME}"
  fi
  if [ -f "${root}/lib/${UNINSTALL_SRC_NAME}" ]; then
    cp "${root}/lib/${UNINSTALL_SRC_NAME}" "${LIB_DIR}/${UNINSTALL_SRC_NAME}"
    chmod +x "${LIB_DIR}/${UNINSTALL_SRC_NAME}"
  fi
  if [ -f "${root}/lib/isiro-compiler-verify-entry.sh" ]; then
    cp "${root}/lib/isiro-compiler-verify-entry.sh" \
      "${LIB_DIR}/isiro-compiler-verify-entry.sh"
    chmod +x "${LIB_DIR}/isiro-compiler-verify-entry.sh"
  fi
  rm -f "${BIN_DIR}/${SERVE_ENTRY_SRC_NAME}" \
        "${BIN_DIR}/${EXTRACT_SRC_NAME}" \
        "${BIN_DIR}/${LAUNCHER_SRC_NAME}"
  # Drop retired entries if present from older installs.
  rm -f "${LIB_DIR}/isiro-cli-entry.sh" "${BIN_DIR}/isiro-cli-entry.sh" \
        "${BIN_DIR}/isiro-compiler-verify-entry.sh"
  if [ -f "${root}/release-manifest.json" ]; then
    cp "${root}/release-manifest.json" "${ISIRO_HOME}/release-manifest.json"
  fi
}

verify_bundle_sha256() {
  local bundle="$1"
  local digest_url="${INSTALL_BASE_URL}/isiro-launcher-${PRODUCT_VERSION}.tar.gz.sha256"
  local expected="" actual
  actual="$(sha256_file "$bundle")"
  if ! expected="$(curl -fsSL "$digest_url" 2>/dev/null | awk '{print $1}')"; then
    warning "Could not fetch bundle digest (${digest_url}); skipping checksum verify."
    return 0
  fi
  if [ "$actual" != "$expected" ]; then
    error "Launcher bundle checksum mismatch (expected ${expected}, got ${actual})."
  fi
  status "Launcher bundle checksum verified."
}

# Cap curl --progress-bar width; full COLUMNS paints a terminal-wide #### line.
curl_download() {
  local dest="$1" url="$2"
  COLUMNS=48 curl --fail --show-error --location --progress-bar \
    -o "$dest" "$url"
}

install_launcher_from_remote() {
  require_tools curl tar
  TEMP_DIR="$(mktemp -d)"
  trap cleanup EXIT
  local bundle_url="${INSTALL_BASE_URL}/isiro-launcher-${PRODUCT_VERSION}.tar.gz"
  local bundle="${TEMP_DIR}/launcher.tar.gz"
  local extract="${TEMP_DIR}/bundle"
  status "Downloading ISIRO launcher ${PRODUCT_VERSION}..."
  curl_download "$bundle" "$bundle_url"
  verify_bundle_sha256 "$bundle"
  mkdir -p "$extract"
  tar -xzf "$bundle" -C "$extract"
  if [ ! -x "${extract}/bin/isiro" ]; then
    error "Invalid launcher bundle (missing bin/isiro)."
  fi
  install_launcher_from_dir "$extract"
}

install_launcher() {
  install_launcher_from_remote
}

install_shell_completion() {
  local comp_src=""
  if [ -f "${LIB_DIR}/${COMPLETION_SRC_NAME}" ]; then
    comp_src="${LIB_DIR}/${COMPLETION_SRC_NAME}"
  else
    warning "${COMPLETION_SRC_NAME} missing; skipping tab completion."
    return 0
  fi
  mkdir -p "${HOME}/.bash_completion.d"
  cp "$comp_src" "${HOME}/.bash_completion.d/isiro"
  local rc
  rc="$(detect_rc_file)"
  append_bash_completion_loader "$rc" || true
}

write_install_receipt() {
  local rc="$1"
  local completion_file="${HOME}/.bash_completion.d/isiro"
  mkdir -p "$ISIRO_HOME"
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$rc" "$completion_file" "${ISIRO_HOME}/install-receipt.json" <<'PY'
import json, sys
rc, completion, out = sys.argv[1:4]
payload = {
    "rc_file": rc,
    "completion_file": completion,
    "path_begin": "# BEGIN ISIRO runtime launcher",
    "path_end": "# END ISIRO runtime launcher",
    "completion_begin": "# BEGIN ISIRO bash completion",
    "completion_end": "# END ISIRO bash completion",
}
with open(out, "w", encoding="utf-8") as fh:
    json.dump(payload, fh, indent=2)
    fh.write("\n")
PY
    return 0
  fi
  cat > "${ISIRO_HOME}/install-receipt.json" <<EOF
{
  "rc_file": "${rc}",
  "completion_file": "${completion_file}",
  "path_begin": "# BEGIN ISIRO runtime launcher",
  "path_end": "# END ISIRO runtime launcher",
  "completion_begin": "# BEGIN ISIRO bash completion",
  "completion_end": "# END ISIRO bash completion"
}
EOF
}

pull_runtime_image() {
  if is_darwin; then
    status "Skipping runtime image pull on macOS (pull on your Linux GPU host before isiro serve)."
    return 0
  fi
  local manifest="${ISIRO_HOME}/release-manifest.json"
  if [ -f "$manifest" ] && command -v python3 >/dev/null 2>&1; then
    eval "$(python3 - "$manifest" <<'PY'
import json, sys
rt = json.load(open(sys.argv[1])).get("runtime") or {}
def sh(k, v):
    if v:
        print(f"{k}='{v}'")
sh("RUNTIME_REGISTRY", rt.get("registry"))
sh("RUNTIME_TAG", rt.get("tag"))
digest = (rt.get("digest") or "").strip()
if digest and not digest.endswith("REPLACE_AT_RELEASE"):
    sh("RUNTIME_DIGEST", digest)
PY
)"
  fi
  local tag_ref="${RUNTIME_REGISTRY}:${RUNTIME_TAG}"
  local ref="$tag_ref"
  if [ -n "$RUNTIME_DIGEST" ] && [ "$RUNTIME_DIGEST" != "sha256:REPLACE_AT_RELEASE" ]; then
    ref="${RUNTIME_REGISTRY}@${RUNTIME_DIGEST}"
  fi
  status "Pulling runtime image ..."
  if docker pull "$ref"; then
    return 0
  fi
  if docker image inspect "$ref" >/dev/null 2>&1 \
      || docker image inspect "$tag_ref" >/dev/null 2>&1; then
    warning "Using locally cached runtime image."
    return 0
  fi
  error "Runtime image not available (${tag_ref}). Check network access to Docker Hub (isiro/isiro-runtime)."
}

cache_runtime_assets() {
  local assets_script="${LIB_DIR}/${INSTALL_ASSETS_SRC_NAME}"
  if [ ! -x "$assets_script" ]; then
    error "Missing ${INSTALL_ASSETS_SRC_NAME} under ${LIB_DIR}. Re-run install.sh."
  fi
  if ! is_linux; then
    status "macOS remote install: cache status/activate on your Linux GPU host (isiro serve is Linux-only)."
    return 0
  fi
  status "Caching runtime assets ..."
  if ! ISIRO_HOME="$ISIRO_HOME" \
      ISIRO_PRODUCT_VERSION="$PRODUCT_VERSION" \
      ISIRO_RUNTIME_REGISTRY="$RUNTIME_REGISTRY" \
      ISIRO_RUNTIME_TAG="$RUNTIME_TAG" \
      ISIRO_RUNTIME_DIGEST="$RUNTIME_DIGEST" \
      bash "$assets_script"; then
    error "Failed to cache runtime assets. Fix errors above and re-run install.sh."
  fi
}

prompt_eula() {
  if eula_already_accepted; then
    return 0
  fi
  echo ""
  echo "By installing you accept the ISIRO EULA (${EULA_VERSION}) at ${EULA_URL}"
  if [ -t 0 ]; then
    printf '%s' "Continue? [y/N] "
    read -r reply
    case "${reply:-}" in
      y|Y|yes|YES) ;;
      *) echo "Installation cancelled."; exit 1 ;;
    esac
  else
    status "Non-interactive install: proceeding (acceptance-by-install)."
  fi
  record_eula_acceptance
}

print_verify_instructions() {
  cat <<EOF
Inspect before running (recommended):

  curl -fsSL ${INSTALL_SCRIPT_URL} -o install.sh
  less install.sh
  curl -fsSL ${INSTALL_SCRIPT_SHA256_URL} -o install.sh.sha256
  sha256sum -c install.sh.sha256          # Linux
  shasum -a 256 -c install.sh.sha256      # macOS
  sh install.sh

View script source:
  ${SCRIPT_SOURCE_URL}

Quick install:
  curl -fsSL ${INSTALL_SCRIPT_URL} | sh
EOF
}

usage() {
  cat <<EOF
Usage: install.sh [--version VER] [--print-verify]

Installs the ISIRO launcher (no sudo). Default location: ~/.isiro/bin/isiro.
Primary docs: https://isiro.ai/docs

Options:
  --version VER     Install a specific product version (default: ${PRODUCT_VERSION})
  --print-verify    Show how to inspect and verify the install script, then exit
  -h, --help        Show this help
EOF
}

post_install_launcher() {
  local prior_ver="${1:-}" rc path_added=0
  rc="$(detect_rc_file)"
  if append_path_line "$rc"; then
    path_added=1
  fi
  install_shell_completion
  write_install_receipt "$rc"
  pull_runtime_image
  cache_runtime_assets
  echo ""
  if [ -n "$prior_ver" ] && [ "$prior_ver" != "$PRODUCT_VERSION" ]; then
    status "ISIRO Runtime upgraded ${prior_ver} to ${PRODUCT_VERSION}."
  else
    status "ISIRO Runtime ${PRODUCT_VERSION} installed."
  fi
  if [ "$path_added" -eq 1 ]; then
    status "Run: source ${rc}   (or open a new terminal), then: isiro --help"
  else
    status "Run: isiro --help"
  fi
  status "Docs: https://isiro.ai/docs"
  status "Free compiler: https://isiro.ai/compiler"
  status "Licensed production: isiro activate <key>"
}

main() {
  local ver="$PRODUCT_VERSION"
  while [ $# -gt 0 ]; do
    case "$1" in
      --version)
        if [ -z "${2:-}" ]; then
          error "missing version"
        fi
        ver="$2"
        shift 2
        ;;
      --print-verify)
        print_verify_instructions
        exit 0
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        error "Unknown option: $1 (try --help)"
        ;;
    esac
  done
  PRODUCT_VERSION="$ver"
  RUNTIME_TAG="$ver"
  local prior_ver=""
  prior_ver="$(read_prior_product_version)"
  preflight_install
  prompt_eula
  install_launcher
  post_install_launcher "$prior_ver"
}

{ main "$@"; }
